/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventamascotas;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Owen
 */
public class EditarUsuario extends javax.swing.JFrame {

    private Usuario objUser;
    private ArrayList<Usuario> listaUsuarios;
    private SerializarObjetos so;
    private File ficheroUsers=new File("Usuarios.txt");
    private int indice;
    
    /**
     * Creates new form EditarUsuario
     */
    public EditarUsuario() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        modelo.addColumn("Cuenta");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Saldo");
        so=new SerializarObjetos();
        listaUsuarios=so.deserializarArrayUser(ficheroUsers);
        for(int i=0;i<listaUsuarios.size();i++){
            if(listaUsuarios.get(i).getTipoUser() != "administrador"){
            modelo.addRow(new Object [] {listaUsuarios.get(i).getCuenta(),listaUsuarios.get(i).getContraseña(),listaUsuarios.get(i).getSaldo()});
            }
        }
        
        listaUsuarios= new ArrayList<Usuario>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelo=new DefaultTableModel();
        jTableUsuarios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCuenta = new javax.swing.JTextField();
        jTextFieldContraseña = new javax.swing.JTextField();
        jTextFieldSaldo = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setText("Editar Usuario");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione el usuario que quiere editar");

        jTableUsuarios.setModel(modelo);
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);

        jLabel3.setText("Cuenta: ");

        jLabel4.setText("Contraseña: ");

        jLabel5.setText("Saldo: ");

        jTextFieldSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSaldoKeyTyped(evt);
            }
        });

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldSaldo)
                                        .addComponent(jTextFieldContraseña)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jLabel1))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jMenu1.setText("Inventario               |");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registro de Ventas               |");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Editar Usuario               |");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Salir");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Inventario i=new Inventario();
        i.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        RegistroVentas rv=new RegistroVentas();
        rv.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        this.dispose();
        IniciarSesion is=new IniciarSesion();
        is.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        objUser=new Usuario();
        objUser.setCuenta(jTextFieldCuenta.getText());
        objUser.setContraseña(jTextFieldContraseña.getText());
        objUser.setTipoUser("Usuario");
        int saldo=Integer.parseInt(jTextFieldSaldo.getText());
        objUser.setSaldo(saldo);
        System.out.println(objUser.getContraseña() + objUser.getCuenta() + objUser.getTipoUser());
        so=new SerializarObjetos();
        listaUsuarios=so.deserializarArrayUser(ficheroUsers);
        System.out.println("deserealizado correctamente");
        listaUsuarios.add(objUser);
        modelo.addRow(new Object [] {objUser.getCuenta(),objUser.getContraseña(),objUser.getSaldo()});
        System.out.println("Usuario aderido correctamente");
        so.serializarArrayUser(ficheroUsers, listaUsuarios);
        jTextFieldCuenta.setText("");
        jTextFieldContraseña.setText("");
        jTextFieldSaldo.setText("");
        System.out.println("Serializado");
        for(int i=0;i<listaUsuarios.size();i++){
           System.out.println(listaUsuarios.get(i).getContraseña() + listaUsuarios.get(i).getCuenta() + listaUsuarios.get(i).getTipoUser()); 
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        objUser=new Usuario();
        if(jTableUsuarios.getSelectedRow()>=0){
            int filaSeleccionada=jTableUsuarios.getSelectedRow();
            so=new SerializarObjetos();
            listaUsuarios=so.deserializarArrayUser(ficheroUsers);
            for (int i = 0; i < listaUsuarios.size() ; i++) {
                if(listaUsuarios.get(i).getCuenta().equalsIgnoreCase(jTableUsuarios.getValueAt(filaSeleccionada, 0).toString())){
                    indice=i;
                    System.out.println(indice);
                }
            }
            objUser.setCuenta(jTextFieldCuenta.getText());
            objUser.setContraseña(jTextFieldContraseña.getText());
            objUser.setTipoUser("Usuario");
            int saldo=Integer.parseInt(jTextFieldSaldo.getText());
            objUser.setSaldo(saldo);
            System.out.println(objUser.getContraseña() + objUser.getCuenta() + objUser.getTipoUser());
            System.out.println("deserealizado correctamente");
            listaUsuarios.set(indice, objUser);
            System.out.println("sustituido en " +indice);
            String [] datos=new String[3];
            datos[0]= objUser.getCuenta();
            datos[1]=objUser.getContraseña();
            String sSaldo=Integer.toString(objUser.getSaldo());
            datos[2] = sSaldo;
            for (int i = 0; i < 3; i++) {
                modelo.setValueAt(datos[i], filaSeleccionada, i);
            }
            so.serializarArrayUser(ficheroUsers, listaUsuarios);
            jTextFieldCuenta.setText("");
            jTextFieldContraseña.setText("");
            jTextFieldSaldo.setText("");
            System.out.println("Serializado");
            for(int i=0;i<listaUsuarios.size();i++){
                System.out.println(listaUsuarios.get(i).getContraseña() + listaUsuarios.get(i).getCuenta() + listaUsuarios.get(i).getTipoUser()); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        if(jTableUsuarios.getSelectedRow()>=0){
            int filaSeleccionada=jTableUsuarios.getSelectedRow();
            so=new SerializarObjetos();
            listaUsuarios=so.deserializarArrayUser(ficheroUsers);
            System.out.println("deserializado correctamente");
            for (int i = 0; i < listaUsuarios.size() ; i++) {
                if(listaUsuarios.get(i).getCuenta().equalsIgnoreCase(jTableUsuarios.getValueAt(filaSeleccionada, 0).toString())){
                    listaUsuarios.remove(i);
                    System.out.println("removido en" + i);
                }
            }
            so.serializarArrayUser(ficheroUsers, listaUsuarios);
            modelo.removeRow(filaSeleccionada);
            jTextFieldCuenta.setText("");
            jTextFieldContraseña.setText("");
            jTextFieldSaldo.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila","Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
        // TODO add your handling code here:
        if(jTableUsuarios.getSelectedRow()>=0){
            int filaSeleccionada=jTableUsuarios.getSelectedRow();
            jTextFieldCuenta.setText(jTableUsuarios.getValueAt(filaSeleccionada, 0).toString());
            jTextFieldContraseña.setText(jTableUsuarios.getValueAt(filaSeleccionada, 1).toString());
            jTextFieldSaldo.setText(jTableUsuarios.getValueAt(filaSeleccionada, 2).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione una fila","Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldCuenta.setText("");
            jTextFieldContraseña.setText("");
            jTextFieldSaldo.setText("");
        }
    }//GEN-LAST:event_jTableUsuariosMouseClicked

    private void jTextFieldSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSaldoKeyTyped
        // TODO add your handling code here:
        char tecleada=evt.getKeyChar();//obtiene el caracter tecleado
        if((tecleada <'0' || tecleada>'9') && tecleada !=32 && tecleada !=8)
        {
            evt.consume(); //no permite consumar la escritura en caso de no cumplir con el if
            JOptionPane.showMessageDialog(null, "Por favor ingrese sólo números","Formato Incorrecto", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldSaldoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private DefaultTableModel modelo;
    private javax.swing.JTextField jTextFieldContraseña;
    private javax.swing.JTextField jTextFieldCuenta;
    private javax.swing.JTextField jTextFieldSaldo;
    // End of variables declaration//GEN-END:variables
}
